services:
  - type: web
    name: affilate
    env: node
    plan: free
    nodeVersion: 18
    buildCommand: npm ci --only=production
    startCommand: node server.js
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: BOT_TOKEN
        sync: false
      - key: WEBHOOK_URL
        sync: false
      - key: ALLOWED_ORIGINS
        value: "*"
    autoDeploy: true
    branch: main
    numInstances: 1
    disk:
      name: data
      mountPath: /opt/render/project/src/data
      sizeGB: 1
